// <auto-generated />
using Cheese.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cheese.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220912232950_updateTableProduct")]
    partial class updateTableProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Cheese.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Cauli cheese. Arguably one of the heroes of British food. Is it really a roast dinner if there’s no super cheesy, crispy-topped, piping hot cauliflower cheese on the table? <br/> Easy to make, you may argue, but follow these handy hints and tips to make it unreal.",
                            ImageUrl = "https://chandraperdana.blob.core.windows.net/cheese/img2.jpg",
                            Name = "Cauliflower cheese",
                            Price = 150000.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            Description = "Stuffed with peppers, spices, potato, cheese and green chutney, chef Maunika Gowardhan's favourite cheese toastie is so very moreish.",
                            ImageUrl = "https://chandraperdana.blob.core.windows.net/cheese/img2.jpg",
                            Name = "Bombay chilli cheese toastie",
                            Price = 139900.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "Three types of melted cheese, hot potatoes and little gherkins on sticks – what's not to love? This recipe has weekend written all over it.",
                            ImageUrl = "https://chandraperdana.blob.core.windows.net/cheese/img3.jpg",
                            Name = "Baked fondue with potato and pickle dippers",
                            Price = 109900.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "Ready-made puff pastry is used to make these easy cheese straws, ready on the table in just over half an hour.",
                            ImageUrl = "https://chandraperdana.blob.core.windows.net/cheese/img4.jpg",
                            Name = "Cheese straws",
                            Price = 150000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
