// <auto-generated />
using Cheese.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cheese.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Cheese.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Asperiores, recusandae suscipit. Eius porro vitae nihil? Velit quaerat architecto at labore voluptatum veritatis exercitationem quis itaque.",
                            ImageUrl = "https://chandraperdana.blob.core.windows.net/cheese/img1.jpg",
                            Name = "Cauliflower cheese",
                            Price = 150000.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            Description = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Asperiores, recusandae suscipit. Eius porro vitae nihil? Velit quaerat architecto at labore voluptatum veritatis exercitationem quis itaque.",
                            ImageUrl = "https://chandraperdana.blob.core.windows.net/cheese/img2.jpg",
                            Name = "Bombay chilli cheese toastie",
                            Price = 139900.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Asperiores, recusandae suscipit. Eius porro vitae nihil? Velit quaerat architecto at labore voluptatum veritatis exercitationem quis itaque.",
                            ImageUrl = "https://chandraperdana.blob.core.windows.net/cheese/img3.jpg",
                            Name = "Potato and pickle dippers",
                            Price = 109900.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Asperiores, recusandae suscipit. Eius porro vitae nihil? Velit quaerat architecto at labore voluptatum veritatis exercitationem quis itaque.",
                            ImageUrl = "https://chandraperdana.blob.core.windows.net/cheese/img4.jpg",
                            Name = "Cheese straws",
                            Price = 150000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
